//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPUtility {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class SettingsTCP : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsTCP defaultInstance = ((SettingsTCP)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsTCP())));
        
        public static SettingsTCP Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string IP4Server {
            get {
                return ((string)(this["IP4Server"]));
            }
            set {
                this["IP4Server"] = value;
            }
        }
    }
}
